### ISSUE TITLE
Store data in db instead of plain text file.

### ISSUE THREAD

**Issue by heymind** [sxwxs/BUPTOfferReaper#1]
It's better to store data in a database for long-term considerations. And I want to work on this.

Here are some ideas.
1. Store in RDBMS ( such as MySQL, SQLite ...)
2. Dialect independent. ( For now, we can just store all records in an embedded SQLite database. But We still need the capability that migrates to a feature-rich DB with no difficulty )

**Comment by sxwxs** [comment]
Thank you for your advice. I'd appreciate it if you could help with this. I prefer SQLite because it uses less memory.

**Comment by heymind** [comment]
#2

**Comment by sxwxs** [comment]
Thank you @heymind
